### ISSUE TITLE
Use Version Tags

### ISSUE THREAD

**Issue by daniel-lucio** [facebookincubator/fizz#14]
Please use tags to get in sync with folly. 
Please also increment the major lib (soversion) when the lib stop being binary compatible

**Comment by Orvid** [comment]
In theory our tooling should have auto-tagged a version on the 10th and 17th, but it doesn't appear to have done so. I've poked it and hopefully it should tag a version on the 24th.

As-to the soversion issue, in general (with a few rare exceptions) Facebook projects make no guarantee of binary compatibility even between two commits made right after each other, and so don't bother updating the soversion (Folly for instance has been at soversion 57 for the last 3 years). Maintaining or even evaluating binary (or even source) compatibility for each commit is something that takes non-trivial extra effort for maintainers, due to how we do development internally. In general, the only guarantee about binary or source compatibility we give for Facebook libraries is that two libraries tagged with the same commit (eg. `v2018.09.17.00`) should be compatible.

**Comment by knekritz** [comment]
Version tags are enabled now https://github.com/facebookincubator/fizz/releases
