### ISSUE TITLE
ios or android support?

### ISSUE THREAD

**Issue by xiazhouquan** [facebookincubator/fizz#32]
How can i build fizz support ios and android by static library,is it possible?

**Comment by mingtaoy** [comment]
Fizz is used in production on ios/android, so I can attest it definitely works on those platforms.

Since Fizz is a CMake project, it should be simply a matter of setting up the appropriate toolchain file (pointing to the iOS, Android cross compilers + headers).

See: https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html

**Comment by xiazhouquan** [comment]
thank you ,I will try it!
