### ISSUE TITLE
please use homebrew to install folly on macOS

### ISSUE THREAD

**Issue by Miigon** [facebookincubator/fizz#48]
Currently `mac-build.sh` builds folly from scratch, but installs it's dependencies from homebrew.

Homebrew already has an up to date version of folly, so it can be installed from homebrew instead of building from scratch.

**Comment by anhuang** [comment]
Hi @Miigon, thank you for the suggestion. Building fizz off a snapshot of folly does not guarantee compilation, since the versions can mismatch. Since moving to homebrew would not solve this issue, we'd prefer to leave it as is for now, especially since we have better support for our current build method.
